sudo: required
language: java
cache:
  directories:
  - "$HOME/.m2"
services:
- docker
jdk:
- openjdk8
env:
- IDRIS_JVM_HOME=${HOME}/bin/idris-jvm
before_install:
- docker pull mmhelloworld/idris:1.3.2
- mkdir -p $HOME/bin/idris-packages $IDRIS_JVM_HOME
- wget https://github.com/mmhelloworld/idris-jvm/releases/download/v1.0-SNAPSHOT-20190914/idris-jvm.zip
- unzip -o idris-jvm.zip -d $HOME/bin
- export PATH=`pwd`/bin/travis:$IDRIS_JVM_HOME/codegen/bin:$HOME/.local/bin:$PATH
- export PROJECT_ROOT=`pwd`
- docker run --name idris mmhelloworld/idris:1.3.2 idris -v && docker cp idris:/.stack-work/install/x86_64-linux/lts-13.21/8.6.5/share/x86_64-linux-ghc-8.6.5/idris-1.3.2/libs/.
  $HOME/bin/idris-packages && docker rm idris
script:
- lsof -ti ":$(cat $IDRIS_JVM_HOME/.idrisjvmport)" | xargs --no-run-if-empty kill
- unzip -o idris-jvm-codegen-launcher/target/idris-jvm.zip -d $HOME/bin
- export IDRIS_JVM_HOME=${HOME}/bin/idris-jvm
- bin/travis/travis_long mvn -pl :idris-jvm-integration-test test -B
before_deploy:
- git config --local user.name mmhelloworld
- git config --local user.email $USER_EMAIL
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: "lpoCR/C+KrH9aRP9v1hdHhDQYuiJddm3sU7ITL0AZt2aFB3V5bOe8urQUtarzJd5GIRy71V3dbg20qj1EA4qrXsjUuVw6C9FE3/uK0i7+N0TWvqUbEDTIviFl+B49PTG3/hC0MzrBk9MkhL++XrNqhuVh5zkUOO+jQstNlP+OzLh2qHf1BsqPbJxUAvfivGwrpX/aE4d0G9rjj/ja6KUOZ5Ob5m+yjIwvYEdjNf6Pa10GbKf5JMBzmMPDqskpeBY7xBrtre8FDIa6ZxZKzhiNw+ynCPZYUcV0Q6NoOFe5dhllO1mYOCQJcPJsfRFbwq8vfguLNHy4VDHfO60uF14hZXtr40BiZSCb9yAlXhK50W5L/TvunadNFUOQZzM1NOFsq2Okil172jqfodu9U1CeHtMWxiFfVtHXhzehO8ihudCQ7Lk594gdX2ASJUG/13Wniy0fMcNho+5D/rvxw4DX05jKUZXO2KnJpHYjT8EMJeVM2FBO46Zhhb3d1LElsnbsL2AVhN3OkNwugcF3aRJAAgPHrE06j8qKeQIvgXrNqZN0p140vJlv6VWQjZkrmQylu80ADjpz62/untY83pgkbcg8oB3HVluQHgoXqiTpweM0uRpvcoXoqZvDU3+T1qLLGcnn8slxn8FxzX2KaPGRdiwIT+HC/hijA5RtuWG7+o="
  file: idris-jvm-codegen-launcher/target/idris-jvm.zip
  skip_cleanup: true
  on:
    repo: mmhelloworld/idris-jvm
    tags: true
