name: Install
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  IDRIS2_PREVIOUS_VERSION: 0.2.2-SNAPSHOT
  IDRIS2_PREVIOUS_VERSION_CLASSIFIER: 20210831
  IDRIS2_TESTS_CG: jvm
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Download previous version
        run: |
          wget https://github.com/mmhelloworld/Idris2/releases/download/v$IDRIS2_PREVIOUS_VERSION-$IDRIS2_PREVIOUS_VERSION_CLASSIFIER/idris2-$IDRIS2_PREVIOUS_VERSION.zip
          unzip idris2-$IDRIS2_PREVIOUS_VERSION -d $HOME/bin
          echo "::add-path::$HOME/bin/idris2-$IDRIS2_PREVIOUS_VERSION/bin"
      - name: Build
        run: mvn --batch-mode install -DskipTests
